apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuinfo
  namespace: ptm
  labels:
    app: gpuinfo
    component: gpuinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpuinfo
  template:
    metadata:
      labels:
        app: gpuinfo
    spec:
      containers:
      - name: gpuinfo
        image: localhost:32000/gpuinfo:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
            nvidia.com/gpu: 1
        ports:
        - containerPort: 12000
